name: CI/CD Pipeline for Homestay Booking System

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2.12 # Adjust to your PHP version
          extensions: mysqli, mbstring

      - name: Start MySQL
        run: |
          sudo service mysql start

      - name: Configure MySQL User
        run: |
          sudo mysql -e "CREATE USER 'test_user'@'localhost' IDENTIFIED BY 'test_password';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'test_user'@'localhost' WITH GRANT OPTION;"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Create Database
        run: |
          mysql -u test_user -ptest_password -e "CREATE DATABASE homestay;"
          mysql -u test_user -ptest_password homestay < tests/database_setup.sql

      - name: Run Tests
        env:
          DB_HOST: localhost
          DB_NAME: homestay
          DB_USER: test_user
          DB_PASSWORD: test_password
        run: |
          php tests/CustomBookingTest.php
