name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: mysqli, sqlite3  # Ensure SQLite3 is installed for testing

    - name: Generate Composer File (If Missing)
      run: |
        if [ ! -f composer.json ]; then
          composer init --name="yourname/project" --type="project" --require-dev="phpunit/phpunit:^9.5" --no-interaction
        fi

    - name: Install Dependencies
      run: composer install --no-scripts --no-progress

    - name: Debug Environment Variables
      run: |
        echo "PHP Version:"
        php -v
        echo "Composer Version:"
        composer --version
        echo "Installed Extensions:"
        php -m

    - name: Run PHPUnit Tests
      run: vendor/bin/phpunit --testdox
